import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { SearchContextProvider } from "@/contexts/SearchContext";

const inter = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} flex flex-col items-center bg-background`}
      >
        <SearchContextProvider>
          <Header />
          <main className="flex flex-col items-center justify-center w-full">
            {children}
          </main>
          <Footer />
        </SearchContextProvider>
      </body>
    </html>
  );
}
